### ISSUE TITLE
plugins should timeout

### ISSUE THREAD

**Issue by hpiwowar** [figshare/Total-Impact#22]
The [plugin API](https://github.com/mhahnel/Total-Impact/wiki/Plugin-requirements) says:

> Plugins should use exponential backoff to handle bad responses from Source APIs. For now, the maximum wait interval should be 30 seconds or so, then an error should be thrown.
- How important is this?  
- Is implementing a maximum wait interval important for the alpha release?  
- Do we care a lot if the maximum wait interval is per plugin call, as opposed to per artifact per plugin call?  

To fulfill this spec, the plugins have to go through all of their incoming artifact ids once first to see how many artifacts pertain to them so they can calculate the maximum wait per http call appropriately.  Then also divide by how many http calls they make per object.  This gets kind of complicated for the crossref plugin, and makes each http call potentially pretty short.  

Would it be ok for alpha if we just implement a 10 second timeout on all http calls?  This guarantees the plugin will return in a finite though potentially long amount of time.

**Comment by jasonpriem** [comment]
It seems important to me that there be some overall timeout for each 
plugin; otherwise an unduly large collection could eat a lot of system 
resources. Seems this would be pretty easy to implement, though; just 
check every iteration of your get-stuff-from-api loop for how much time 
has elapsed, and break if it's been too long.

The bigger problem is that we don't have any way to indicate that _part_ 
of a collection has been updated--it's all or nothing. So that means 
that plugins should have a way to then retry individual calls after a 
short wait. Otherwise, you might have one borked response out of every 
100 or whatever, but the plugin returns "fail" for the whole collection 
and we have to redo all of them later.

**Comment by hpiwowar** [comment]
ok, good point, I can do that.

Yeah, I hear you on total failure.  Fine for alpha, let's revisit later.  Plugins can handle it themselves if they want in the meantime by doing caching.

**Comment by hpiwowar** [comment]
done.  Could do with regression tests for this, though, since unlikely to detect if it breaks at some point.
