### ISSUE TITLE
Changelog from github

### ISSUE THREAD

**Issue by dartar** [figshare/Total-Impact#56]
Instead of manually maintaining a changelog in the page footer, we should read it from CHANGES.md, and maybe even provide a link to the whole commit history on GitHub

**Comment by jasonpriem** [comment]
We do :)
See line 45 in footer.php; the link there points to CHANGES.md on GitHub, and anyone who knows what a commit history is should be able to find it from there with ease.

I thought about using the GitHub API to actually display the commit history there, but I thought that might be less informative, since there are lots of low-level commits.
